#!/usr/bin/env python3
"""Secondary engine validation scaffold for TB transmission inference.

This script probes optional engines (TransPhylo and BactDating), executes the
R scaffold runner, and writes a normalized JSON artifact that downstream APIs
can surface without implying that secondary inference has been completed.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXPORTS = ROOT / "exports"
R_SCRIPT = ROOT / "outbreaker2" / "run_secondary_engines.R"
OUT_JSON = EXPORTS / "secondary_engine_validation.json"


def _iso_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _find_rscript() -> str | None:
    direct = shutil.which("Rscript")
    if direct:
        return direct

    candidates = [
        Path("C:/Program Files/R"),
        Path("C:/Program Files (x86)/R"),
    ]
    for base in candidates:
        if not base.exists():
            continue
        versions = sorted(base.glob("R-*/bin/Rscript.exe"), reverse=True)
        if versions:
            return str(versions[0])
        versions_x64 = sorted(base.glob("R-*/bin/x64/Rscript.exe"), reverse=True)
        if versions_x64:
            return str(versions_x64[0])

    return None


def _write_result(payload: dict) -> None:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def main() -> None:
    rscript = _find_rscript()

    result: dict = {
        "generated_at": _iso_now(),
        "status": "not_run",
        "scaffold_version": "1.0",
        "inputs": {
            "outbreaker_network": str((EXPORTS / "transmission_network.json").as_posix()),
            "outbreaker_summary": str((EXPORTS / "outbreaker_summary.json").as_posix()),
            "optional_tree_newick": str((EXPORTS / "outbreaker_phylo.nwk").as_posix()),
            "optional_dates_csv": str((EXPORTS / "cases.csv").as_posix()),
        },
        "engines": {
            "transphylo": {"status": "unknown"},
            "bactdating": {"status": "unknown"},
        },
        "consensus": {
            "status": "pending_secondary_outputs",
            "agreement": None,
            "confidence": "unknown",
        },
        "notes": [
            "This is a scaffold lane: it validates readiness and writes a stable artifact shape.",
            "Full secondary inference needs a timed phylogeny (e.g. exports/outbreaker_phylo.nwk).",
        ],
    }

    if not rscript:
        result["status"] = "blocked"
        result["notes"].append("Rscript not found; install R and rerun secondary validation.")
        _write_result(result)
        print(json.dumps(result, indent=2))
        return

    env = os.environ.copy()
    user_r_lib = Path.home() / "Documents" / "R" / "win-library" / "4.6"
    env.setdefault("R_LIBS_USER", str(user_r_lib))

    proc = subprocess.run(
        [rscript, str(R_SCRIPT)],
        cwd=str(ROOT),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        timeout=600,
        check=False,
    )

    result["rscript_path"] = rscript
    result["runner_exit_code"] = proc.returncode
    result["runner_output_tail"] = "\n".join(proc.stdout.splitlines()[-20:])

    if OUT_JSON.exists():
        # Keep artifact generated by R runner; just print it for logs.
        payload = json.loads(OUT_JSON.read_text(encoding="utf-8"))
        print(json.dumps(payload, indent=2))
        return

    if proc.returncode == 0:
        result["status"] = "completed"
    else:
        result["status"] = "failed"
        result["notes"].append("R secondary engine runner exited non-zero; see runner_output_tail.")

    _write_result(result)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()

